import * as pulumi from "@pulumi/pulumi";
import * as vault from "@pulumi/vault";
import {buildUrn, URN_TYPE} from "../../constants/pulumi";

export type VaultPulumiAuthArgs = {
    rootProvider: vault.Provider,
    address: string | pulumi.Output<string>;
}

export class VaultPulumiAuth extends pulumi.ComponentResource {
    readonly provider: vault.Provider;
    readonly approleCreds: { secretId: pulumi.Output<string>, roleId: pulumi.Output<string> }

    constructor(name: string, args: VaultPulumiAuthArgs, opts?: pulumi.ComponentResourceOptions) {
        super(buildUrn(URN_TYPE.Configuration, "VaultPulumiAuth"), name, {}, opts)

        const approleBackend = new vault.AuthBackend("approle-backend", {
            description: "Automatically Generated by Pulumi",
            type: "approle",
            tune: {
                defaultLeaseTtl: "10m",
                // TODO: Make sure this makes sense.
                maxLeaseTtl: "24h"
            }
        }, {parent: this, provider: args.rootProvider})

        const pulumiPolicy = new vault.Policy("pulumi-policy", {
            policy: `
# Full access to kv and database secret engines
path "kv2/*" { capabilities = ["create", "read", "update", "delete", "list"] }
path "auth/*" { capabilities = ["create", "read", "update", "delete", "list"] }
path "database/*" { capabilities = ["create", "read", "update", "delete", "list"] }
path "pulumi/*" { capabilities = ["create", "read", "update", "delete", "list"] }

# Create and Manage kv and database secret engines
path "sys/mounts" { capabilities = ["read", "list"] }
path "sys/mounts/kv2" { capabilities = ["create", "read", "update", "delete", "list"] }
path "sys/mounts/kv2/*" { capabilities = ["create", "read", "update", "delete", "list"] }
path "sys/mounts/database" { capabilities = ["create", "read", "update", "delete", "list"] }
path "sys/mounts/database/*" { capabilities = ["create", "read", "update", "delete", "list"] }

path "sys/remount" {capabilities = ["create", "update", "read", "delete", "list"]}

# Create Discord Auth Method
path "sys/auth/discord" { capabilities = [ "create", "read", "update", "delete", "sudo" ] }
# Configure the Discord Auth method
path "sys/auth/discord/*" { capabilities = [ "create", "read", "update", "delete", "list" ] }
path "sys/auth" { capabilities = ["read", "list"] }
path "sys/mounts/auth/discord/*" { capabilities = [ "create", "read", "update", "delete", "list" ] }


# Write ACL policies (prefixed with pulumi- to prevent improper access)
path "sys/policies/acl/pulumi-*" { capabilities = [ "create", "read", "update", "delete", "list" ] }

# List available secrets engines to retrieve accessor ID
path "sys/mounts" { capabilities = [ "read" ] }
            `,
            name: "pulumi"
        }, {parent: this, provider: args.rootProvider})

        const pulumiApproleId = new vault.approle.AuthBackendRole("pulumi-approle", {
            roleName: "pulumi-approle",
            tokenPolicies: [pulumiPolicy.name]
        }, {parent: this, provider: args.rootProvider, dependsOn: [approleBackend]})

        const pulumiApproleSecret = new vault.approle.AuthBackendRoleSecretId("pulumi-approle-secret", {
            roleName: pulumiApproleId.roleName,
        }, {parent: this, provider: args.rootProvider})

        this.provider = new vault.Provider("provider", {
            address: args.address,
            token: "",
            authLogin: {
                path: "/auth/approle/login",
                parameters: {
                    secret_id: pulumiApproleSecret.secretId,
                    role_id: pulumiApproleId.roleId
                }
            }
        })
        this.approleCreds = {
            secretId: pulumiApproleSecret.secretId,
            roleId: pulumiApproleId.roleId
        }
    }
}