#
#   As a note: this stack should contain only services which are required to stand up the primary stack
#
version: '3.8'
{{ $v := (datasource "config").vault }}
# Create a hash of the config file to use as a "tag"
# This will prevent issues when re-deploying with a changed configuration
{{ $vaultConfigHash := crypto.SHA1 (file.Read "/mnt/vault/vault.config.hcl") }}

configs:
  vault-config-{{ $vaultConfigHash }}:
    file: ./configs/vault/vault.config.hcl

volumes:
  vault-data:

networks:
  traefik-ingress:
    external: true
  config-net:
    external: true

services:
  vault:
    image: vault:1.9.3

    configs:
      - source: vault-config-{{ $vaultConfigHash }}
        target: /vault/config/default.hcl

    volumes:
      - type: volume
        source: vault-data
        target: /vault/file

    command: server

    networks:
      - traefik-ingress
      - config-net

    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.{{ $v.ingress.label }}.rule=Host(`{{ $v.ingress.domain }}`)
        - traefik.http.routers.{{ $v.ingress.label }}.service={{ $v.ingress.label }}@docker
        - traefik.http.routers.{{ $v.ingress.label }}.tls=true
        - traefik.http.routers.{{ $v.ingress.label }}.tls.certresolver=lets-encrypt-dns
        - traefik.http.services.{{ $v.ingress.label }}.loadbalancer.server.port=8200
