version: '3.8'

x-logging:
  &default-logging
  driver: fluentd
  options:
    - fluentd-async: true

volumes:
  traefik-data:
  postgres-data:
  redis-data:
  influx-data:

networks:
  proxy:
    driver: overlay
  timescale-net:
    driver: overlay
  traefik-ingress:
    external: true
  monitoring-net:
    driver: overlay
  sprocket-platform:
    driver: overlay

secrets:
  Minio.AccessKey:
    external: true
  Minio.SecretKey:
    external: true

#{{ $traefikStaticHash := crypto.SHA1 (file.Read "/mnt/traefik/traefik.static.yml") }}
#{{ $traefikDynamicHash := crypto.SHA1 (file.Read "/mnt/traefik/traefik.dynamic.yml") }}
#{{ $fluentdHash := crypto.SHA1 (file.Read "/mnt/fluentd/fluentd.conf") }}
#{{ $telegrafLocalHash := crypto.SHA1 (file.Read "/mnt/telegraf/telegraf.local.conf") }}
#{{ $telegrafGlobalHash := crypto.SHA1 (file.Read "/mnt/telegraf/telegraf.global.conf") }}

configs:
  traefik-static-{{ $traefikStaticHash }}:
    file: ./configs/traefik/traefik.static.yml
  traefik-dynamic-{{ $traefikDynamicHash }}:
    file: ./configs/traefik/traefik.dynamic.yml
  fluentd-{{ $fluentdHash }}:
    file: ./configs/fluentd/fluentd.conf
  telegraf-local-{{ $telegrafLocalHash }}:
    file: ./configs/telegraf/telegraf.local.conf
  telegraf-global-{{ $telegrafGlobalHash }}:
    file: ./configs/telegraf/telegraf.global.conf

services:
  ###########################
  #      Primary Ingress    #
  ###########################
  # TODO: https://github.com/thomseddon/traefik-forward-auth
  # Reverse Proxy & HTTPS Cert Automation
  traefik:
    image: traefik:2.5
    #{{ $traefik := (datasource "config").traefik }}
    #{{ $traefikSecure := (datasource "vault" "cubbyhole/traefik") }}
    environment:
      - TRAEFIK_API=true
      - DO_AUTH_TOKEN={{ $traefikSecure.do_auth_token }}

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - traefik-data:/data

    logging: *default-logging

    configs:
      - source: traefik-static-{{ $traefikStaticHash }}
        target: /traefik.yaml
      - source: traefik-dynamic
        target: /traefik.dynamic.yml-{{ $traefikDynamicHash }}

    deploy:
      labels:
        - traefik.enabled=true
        - traefik.http.routers.{{ $traefik.ingress.label }}.rule=Host(`{{ $traefik.ingress.domain }}`)
        - traefik.http.routers.{{ $traefik.ingress.label }}.service=api@internal
        - traefik.http.routers.{{ $traefik.ingress.label }}.tls=true
        - traefik.http.routers.{{ $traefik.ingress.label }}.tls.certresolver=lets-encrypt-dns
        - traefik.http.services.{{ $traefik.ingress.label }}.loadbalancer.server.port=9999
      placement:
        constraints:
          # Tweak this to ensure it always remains on the same node
          - "node.hostname=={{ $traefik.node_hostname }}"
    command: --configFile=/traefik.static.yml

    networks:
      - proxy
      - traefik-ingress

  ###########################
  #     Ingress Helpers     #
  ###########################
  # Abstract the docker socket away a bit to keep it safe
  socket-proxy:
    image: tecnativa/docker-socket-proxy
    environment:
      CONTAINERS: 1
      SERVICES: 1
      SWARM: 1
      NETWORKS: 1
      TASKS: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy
    logging: *default-logging
    deploy:
      placement:
        constraints:
          - "node.role==manager"

  ###########################
  #      Infrastructure     #
  ###########################
  # Postgres + Time Series
  timescaledb:
    #{{ $timescale := (datasource "config").timescale }}

    #TODO: https://www.vaultproject.io/api-docs/secret/databases/postgresql
    image: timescale/timescaledb:latest-pg12

    volumes:
      - source: postgres-data
        target: /var/lib/postgresql/data

    networks:
      - timescale-net
      - monitoring-net
    deploy:
      labels:
        - traefik.enabled=true
        - traefik.tcp.routers.{{ $timescale.ingress.label }}.rule=HostSNI(`{{ $timescale.ingress.domain }}`)
        - traefik.tcp.routers.{{ $timescale.ingress.label }}.tls=true
        - traefik.tcp.routers.{{ $timescale.ingress.label }}.tls.certresolvers=lets-encrypt-dns
        - traefik.tcp.routers.{{ $timescale.ingress.label }}.entrypoint=tcp-nonstandard
        - traefik.tcp.services.{{ $timescale.ingress.label }}.loadbalancer.server.port=5432
      placement:
        constraints:
          - node.hostname=={{ $timescale.node_hostname }}

    logging: *default-logging

  # S3 Compatible Object Storage
  minio:
    # TODO: Investigate https://github.com/StatCan/vault-plugin-secrets-minio
    #{{ $minio := (datasource "config").minio }}
    image: minio/minio:RELEASE.2022-02-12T00-51-25Z
    volumes:
      - type: "{{ $minio.mount.type }}"
        source: "{{ $minio.mount.source }}"
        target: /data

    networks:
      - traefik-ingress
      - sprocket-platform

    # TODO: Mount Vault Credentials
    secrets:
      - source: Minio.SecretKey
        target: /run/secrets/secret_key
      - source: Minio.AccessKey
        target: /run/secrets/access_key

    environment:
      #{{ if eq $minio.console.enabled true }}
      MINIO_BROWSER_REDIRECT_URL: "{{ $minio.console.domain }}"
      #{{ end }}

    command: server /data --console-address ":9001"

    logging: *default-logging

    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.{{ $minio.ingress.label }}.rule={{ $minio.ingress.domain }}
        - traefik.http.routers.{{ $minio.ingress.label }}.tls=true
        - traefik.http.routers.{{ $minio.ingress.label }}.tls.certresolver=lets-encrypt-dns
        - traefik.http.services.{{ $minio.ingress.label }}.loadbalancer.server.port=9000
        - traefik.http.routers.{{ $minio.ingress.label }}.service={{ $minio.ingress.label }}@docker
        #{{ if eq $minio.console.enabled true }}
        - traefik.http.routers.{{ $minio.ingress.label }}-console.rule={{ $minio.console.domain }}
        - traefik.http.routers.{{ $minio.ingress.label }}-console.tls=true
        - traefik.http.routers.{{ $minio.ingress.label }}-console.tls.certresolver=lets-encrypt-dns
        - traefik.http.routers.{{ $minio.ingress.label }}.service={{ $minio.ingress.label }}-console@docker
        - traefik.http.services.{{ $minio.ingress.label }}-console.loadbalancer.server.port=9001
        #{{ end }}
      placement:
        constraints:
          - node.hostname=={{ $minio.node_hostname }}

  # Message Broker
  rabbitmq:
    #{{ $rabbitmq := (datasource "config").rabbitmq }}

    # TODO: https://www.vaultproject.io/api-docs/secret/rabbitmq
    hostname: rabbitmq

    image: rabbitmq:3.9.9-management-alpine

    volumes:
      - source: rabbitmq_data
        target: /var/lib/rabbitmq

    networks:
      - sprocket-platform
      - monitoring-net
      - traefik-ingress

    logging: *default-logging

    deploy:
      labels:
        - traefik.enabled=true
        - traefik.tcp.routers.{{ $rabbitmq.ingress.label }}.rule=HostSNI(`{{ $rabbitmq.ingress.domain }}`)
        - traefik.tcp.routers.{{ $rabbitmq.ingress.label }}.tls=true
        - traefik.tcp.routers.{{ $rabbitmq.ingress.label }}.tls.certresolvers=lets-encrypt-dns
        - traefik.tcp.routers.{{ $rabbitmq.ingress.label }}.entrypoint=tcp-nonstandard
        - traefik.tcp.services.{{ $rabbitmq.ingress.label }}.loadbalancer.server.port=5672
        #{{ if eq $rabbitmq.console.enabled true }}
        - traefik.http.routers.{{ $rabbitmq.ingress.label }}-console.rule={{ $rabbitmq.console.domain }}
        - traefik.http.routers.{{ $rabbitmq.ingress.label }}-console.tls=true
        - traefik.http.routers.{{ $rabbitmq.ingress.label }}-console.tls.certresolver=lets-encrypt-dns
        - traefik.http.routers.{{ $rabbitmq.ingress.label }}.service={{ $rabbitmq.ingress.label }}-console@docker
        - traefik.http.services.{{ $rabbitmq.ingress.label }}-console.loadbalancer.server.port=15672
        #{{ end }}
      placement:
        constraints:
          - node.hostname=={{ $rabbitmq.node_hostname }}

  # In Memory Key/Value Store
  redis:
    #{{ $redis := (datasource "config").redis }}
    # Matchmaking Service requires redis json
    image: redislabs/rejson:latest

    # TODO: Inspect https://github.com/fhitchen/vault-plugin-database-redis
    command:
      - --loadmodule /usr/lib/redis/modules/rejson.so
      - --loadmodule /usr/lib/redis/modules/redisearch.so

    volumes:
      - source: redis-data
        target: /data

    networks:
      - monitoring-net
      - sprocket-platform

    logging: *default-logging

    deploy:
      labels:
        - traefik.enabled=true
        - traefik.tcp.routers.{{ $redis.ingress.label }}.rule=HostSNI(`{{ $redis.ingress.domain }}`)
        - traefik.tcp.routers.{{ $redis.ingress.label }}.tls=true
        - traefik.tcp.routers.{{ $redis.ingress.label }}.tls.certresolvers=lets-encrypt-dns
        - traefik.tcp.routers.{{ $redis.ingress.label }}.entrypoint=tcp-nonstandard
        - traefik.tcp.services.{{ $redis.ingress.label }}.loadbalancer.server.port=6379
      placement:
        constraints:
          - node.hostname=="{{ $redis.node_hostname }}"

  ###################################
  # Metrics & Logging Visualization #
  ###################################
  # Dashboarding and Alerting System
  grafana:
    #{{ $grafana := (datasource "config").grafana }}
    #{{ $grafanaSecure := (datasource "vault" "cubbyhole/grafana") }}
    image: grafana/grafana:main

    environment:
      - GF_DATABASE_TYPE=postgres
      - GF_DATABASE_URL= "" # TODO: Mount from Vault?
      - GF_INSTALL_PLUGINS=redis-app
      - # addr=redis:6379,db=[num],ssl=false,password=[password],user=[username]
      - GF_REMOTE_CACHE_CONNSTRING= "" # TOOD: Mount from Vault?
      - GF_REMOTE_CACHE_TYPE=redis
      - GF_SERVER_DOMAIN={{ $grafana.ingress.domain }}
      - GF_SMTP_ENABLED={{ $grafana.smtp.enabled }}
      #{{ if eq $g.smtp.enabled "true" }}
      - GF_SMTP_FROM_ADDRESS={{ $grafana.smtp.from_address }}
      - GF_SMTP_HOST={{ $grafana.smtp.host }}
      - GF_SMTP_PASSWORD={{ $grafanaSecure.smtp.password }} # TODO: Mount from Vault
      - GF_SMTP_USER={{ $grafana.smtp.user }} # TODO: Mount from vault?
      #{{ end }}

    deploy:
      labels:
        - traefik.enabled=true
        - traefik.http.routers.{{ $grafana.ingress.label }}.rule={{ $grafana.console.domain }}
        - traefik.http.routers.{{ $grafana.ingress.label }}.tls=true
        - traefik.http.routers.{{ $grafana.ingress.label }}.tls.certresolver=lets-encrypt-dns
        - traefik.http.routers.{{ $grafana.ingress.label }}.service={{ $grafana.ingress.label }}@docker
        - traefik.http.services.{{ $grafana.ingress.label }}.loadbalancer.server.port=3000
      placement:
        constraints:
          - "node.hostname=={{ $grafana.node_hostname }}"

    logging: *default-logging

    networks:
      - monitoring-net
      - traefik-ingress
      - timescale-net


  ###################################
  #   Metrics & Logging Datastores  #
  ###################################
  # Time Series Database - Used for internal analytics & metrics collection
  influx:
    #{{ $influx := (datasource "config").influx }}
    #{{ $influxSecure := (datasource "vault" "cubbyhole/influx") }}
    image: influxdb:alpine

    environment:
      DOCKER_INFLUXDB_INIT_BUCKET: "{{ $influx.default.bucket }}"
      DOCKER_INFLUXDB_INIT_ORG: "{{ $influx.default.org }}"
      DOCKER_INFLUXDB_INIT_PASSWORD: password # TODO: Vault
      DOCKER_INFLUXDB_INIT_USERNAME: "{{ $influx.default.username }}"

    volumes:
      - type: volume
        source: influx-data
        target: /var/lib/influxdb2

    networks:
      - monitoring-net
      - sprocket-platform
      - traefik-ingress

    logging: *default-logging

    deploy:
      placement:
        constraints:
          - "node.hostname=={{ $influx.node_hostname }}"
      labels:
        - traefik.enabled=true
        - traefik.tcp.routers.{{ $influx.ingress.label }}.rule=HostSNI(`{{ $influx.ingress.domain }}`)
        - traefik.tcp.routers.{{ $influx.ingress.label }}.tls=true
        - traefik.tcp.routers.{{ $influx.ingress.label }}.tls.certresolvers=lets-encrypt-dns
        - traefik.tcp.routers.{{ $influx.ingress.label }}.entrypoint=tcp-nonstandard
        - traefik.tcp.services.{{ $influx.ingress.label }}.loadbalancer.server.port=8086

  # Log Aggregator and Store
  loki:
    #{{ $loki := (datasource "config").loki }}
    image: grafana/loki:latest

    volumes:
      - type: "{{ $loki.mount.type }}"
        source: "{{ $loki.mount.source }}"
        target: /data

    # TODO: ensure that this doesn't create an infinite loop
    logging: *default-logging

    networks:
      - monitoring-net

    deploy:
      placement:
        constraints:
          - "node.hostname=={{ $loki.node_hostname }}"

  ###################################
  #   Metrics & Logging Collectors  #
  ###################################
  # Log Collector
  fluentd:
    # Use custom image that has the loki plugin installed
    # See https://github.com/SprocketBot/fluentd-loki
    image: actualsovietshark:/fluentd-loki:latest
    environment:
                        ## Escape Gomplate
      FLUENTD_HOSTNAME: "{{"{{"}}.Node.Hostname{{"}}"}}"
    networks:
      - monitoring-net

    ports:
      - target: 24224
        published: 24224
        mode: host
        protocol: tcp

    configs:
      - source: fluentd-{{ $fluentdHash }}
        target: /fluentd/etc/fluent.conf

    deploy:
      # Everybody gets a fluentd
      mode: global
      update_config:
        parallelism: 0
      resources:
        limits:
          memory: 256mb
          cpus: 0.25

  ####
  ### TODO: Telegraf Configuration Credentials
  ### TODO: Telegraf host metrics
  ###   https://community.influxdata.com/t/how-can-we-collect-host-machine-metrics-while-telegraf-is-running-in-docker-container/12005
  ####

  # Metrics Collector, this instance collects from services
  telegraf:
    image: telegraf:latest
    networks:
      - monitoring-net

    logging: *default-logging

    # https://www.vaultproject.io/api/secret/databases/influxdb
    # TODO: Figure out a better way to provide influx credentials

    configs:
      - source: telegraf-local-{{ $telegrafLocalHash }}
        target: /etc/telegraf/telegraf.conf

  # Metrics Collector, this instance collects from nodes
  telegraf-global:
    image: telegraf:latest
    # https://www.vaultproject.io/api/secret/databases/influxdb
    # TODO: Figure out a better way to provide influx credentials

    deploy:
      mode: global
      update_config:
        parallelism: 0
      resources:
        limits:
          memory: 256mb
          cpus: 0.25

    configs:
      - source: telegraf-global-{{ $telegrafGlobalHash }}
        target: /etc/telegraf/telegraf.conf


    logging: *default-logging

    # TODO: find a better way to collect docker metrics.
    # https://www.influxdata.com/blog/docker-run-telegraf-as-non-root/
    user: root
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true

  ###################################
  #         Platform Services       #
  ###################################
  bot-service:
    -

  matchmaking-service:
    -

  replay-parse-service:
    -

  server-analytics:
    -

  core:
    -

  web:
    -
