config:
  SprocketInfrastructure:base-hostname: sprocket-testing-1.h.hl1.io
  SprocketInfrastructure:traefik-ca-server: https://stepca.i.hl1.io/acme/acme/directory
  SprocketInfrastructure:traefik-trust-ca: ../certs/stepca-root.crt
  SprocketInfrastructure:vault-s3-access-key:
    secure: AAABAEgVUIYHKrsiVlcp/c3A/mhGJ7oMxU8K1ysn/tsclQRIbVN68q2yRN2xseWEBnePOw==
  SprocketInfrastructure:vault-s3-bucket: vault
  SprocketInfrastructure:vault-s3-endpoint: https://s3.itsbrian.dev
  SprocketInfrastructure:vault-s3-secret-key:
    secure: AAABAMyg09eWWVb8cbfheAVcH2hkQtphz9YIrg8wu7Ob3axpm5kRTCVfDgvLK+K+b6Qp0KbSqy3snbtuZ0Lz+97tlWtvBz0p
  docker:host: ssh://sprocket@sprocket-testing-1.h.hl1.io
